### ISSUE TITLE
Circleguard showing valid api key as invalid

### ISSUE THREAD

**Issue by Hexality** [circleguard/circleguard#105]
Hi, I tried to use cg, but even creating the key in the exact same way  it asks to in the tutorial, circleguard shows the api key as invalid when trying to load through handler `circleguard://m=1839761&u=18539649`

**Comment by tybug** [comment]
you didn't use the right api key somehow. First thing to check: did you include a newline or other extraneous characters at the beginning or end of the api key in the settings? Remove those if so. If that doesn't work dm me on discord and we'll work it out: tybug#8490

**Comment by tybug** [comment]
turns out cg wasn't persisting the api key or ever writing it to settings. OP solved this by running cg as administrator, which for some reason allowed it to write to settings. 

`QSettings` uses the registry behind the scenes on windows, so my initial guess is that some other program locked down access to the registry on this particular machine. I'm not knowledgable enough about the windows OS to say if that is a real possibility or not, but it's what I'm going with. Something to keep in mind for future similar issues, in any case.
