### ISSUE TITLE
Error after starting two identical loadables "Map"

### ISSUE THREAD

**Issue by Riddalmorning** [circleguard/circleguard#112]
To reproduce this, create 2 same loadables "Map" like this:
![Screenshot_4](https://user-images.githubusercontent.com/75766843/101850228-ca395e80-3b72-11eb-9b26-4baec36b0426.png)
And choose something to investigate, but not "similarity" (it works normal)
Last message and error:
![Screenshot_6](https://user-images.githubusercontent.com/75766843/101850379-15537180-3b73-11eb-9362-567fb865a8e0.png)
Look like the problem in skipping, so you need to start a map, that has no replay in top 100 (for example 240011)

**Comment by tybug** [comment]
If a problematic (non-downloadable) replay is present in multiple loadables, we tried to remove it from a list twice, leading to this error. Also occurs when you have a replay map and map, as below. Fixed in f6282041c97eac120789e245f7817deb6f8faaef

![image](https://user-images.githubusercontent.com/31628143/101851054-dbf61400-3b28-11eb-8007-0d0fbe7a9fab.png)
