### ISSUE TITLE
"Copy Template" button gives superfluous outputs?

### ISSUE THREAD

**Issue by myangelaku** [circleguard/circleguard#115]
I believe that this button was added before the OsuReportBot (I believe those templates exist for Reddit reports)/the detailed score page were implemented, so there are a few superfluous lines in the output now.
An example output looks like this:
```
[osu!std] marinati | Timewarp

Profile: https://osu.ppy.sh/users/11078134

Map: https://osu.ppy.sh/b/1264192

replay download: https://osu.ppy.sh/scores/osu/3112210438/download

open in circleguard: circleguard://m=1264192&u=11078134&m1=DT

10.7 cv average frametime according to https://github.com/circleguard/circleguard
```
I don't really think that the profile has to be linked since the OsuReportBot I mentioned links the profile in question as well as important information about them:

![firefox_Vd2lo376WU](https://user-images.githubusercontent.com/28674643/102392245-1c490c80-3fd7-11eb-8fd7-f24df73ed59a.png)

On top of that, linking the map is unnecessary as well in my opinion since the replay download link links to the score page from which the map can be opened easily. 

Also I think that the Replay Download line as well as the the "/download" should be replaced with just the score page as well since the link just redirects to the detailed score page.

**Comment by tybug** [comment]
osureportbot predates circleguard actually, but I kept the profile link there because I think it's important information and I don't want to make people go down to the comments to get it, though I could be persuaded that having it in the comments is good enough. The map is a good point with the new score page. I've actually sort of intentionally kept the /download so I can tell who uses circleguard just from the link because nobody else uses the /download part anymore. I don't care too much though so I should probably remove that as well

**Comment by tybug** [comment]
done in 3ffd7cdaff97c2c47341bda833ae94c377ce281a (removed map link and /download, kept profile link)
