### ISSUE TITLE
Add "Open Circleguard folder" button

### ISSUE THREAD

**Issue by myangelaku** [circleguard/circleguard#175]
I guess somewhere in the settings tab
https://discord.com/channels/532476765860265984/539956865245904906/922176341804195880

**Comment by Stedoss** [comment]
Is there a particular design/location for this button @tybug? I can have a go at implementing it

**Comment by tybug** [comment]
yep, just another button on the settings tab, next to "open advanced settings" and "sync settings". It should probably open the application support folder (or appdata/roaming for windows). Unfortunately, due to a well-entrenched mistake by me, circleguard's storage dirs are at the base level of application support instead of a nested subdir (we store at `application support/cache` instead of `application support/circleguard/cache` like we should), so best we can do is probably opening application support itself.

**Comment by tybug** [comment]
closed by https://github.com/circleguard/circleguard/pull/184
