### ISSUE TITLE
linux port?

### ISSUE THREAD

**Issue by Pai-en** [circleguard/circleguard#178]
mayhaps

**Comment by Stedoss** [comment]
Feel free to build/run from source, we try to assure everything runs and works on Linux, we just don't package for specific distros. Maybe flatpak/snap is something we might look into in the future.

**Comment by tybug** [comment]
like @Stedoss said, we already support linux, though it's a bit of a pain since you have to [build or run from source](https://github.com/circleguard/circleguard#building-from-source). I don't have the bandwidth to provide linux builds currently since I don't own a linux machine, but I do support linux and will fix any issues reported.
