### ISSUE TITLE
right click -> copy text terminal highlight is different color from accent

### ISSUE THREAD

**Issue by tybug** [circleguard/circleguard#26]
A nitpick, but right clicking the terminal and selecting "select all" will highlight all the text in a light grey instead of our blue accent. Not sure if it uses a different style or what.

**Comment by InvisibleSymbol** [comment]
This happens because of your reimplantation of `mousePressEvent`. After clicking "select all", the event will be processed and the focus of the terminal will be lost (since you clicked on the pop-up). 
Some solutions would be to remove the code (gui.py ln130-134) or to change the inactive selected color, but both seemed to cause other unwanted side effects, so I choose to just ignore QTextEdit instances. This fixes the problem but makes it impossible to deselect QTextEdit. (Still the better than the other solutions imo)

**Comment by tybug** [comment]
Since there's no visual indication while a QTextEdit is selected, and you can still switch focus fine, I think this solution works perfectly well. Thanks
